<?php

namespace Mathias\Bundle\CiqualBundle\Repository;

/**
 * AlimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlimentRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $like
     * @return array
     * cette fonction sert à chercher les aliment dont le nom contient la chaîne de caractère passé en paramètre
     * un tableau sous la forme [id, text] est renvoyé
     */
    public function findByLike($like)
    {
        $q = $this->createQueryBuilder('aliment')
            ->select('aliment.id, aliment.nom text')
            ->where('aliment.nom LIKE :val')
            ->setParameter('val', '%' . $like . '%');

        return $q->getQuery()->getResult();
    }
}
