<?php

namespace Mathias\Bundle\CiqualBundle\Repository;

/**
 * AlimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlimentRepository extends \Doctrine\ORM\EntityRepository
{
}
