<?php

namespace Mathias\Bundle\CiqualBundle\Repository;

/**
 * AlimentElementNutritifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlimentElementNutritifRepository extends \Doctrine\ORM\EntityRepository
{
}
