<?php

namespace Mathias\Bundle\CiqualBundle\Repository;

/**
 * AlimentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlimentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLike($like)
    {
        $q = $this->createQueryBuilder('aliment')
            ->select('aliment.id, aliment.nom text')
            ->where('aliment.nom LIKE :val')
            ->setParameter('val', '%' . $like . '%');

        return $q->getQuery()->getResult();
    }
}
