mathias_ciqual_homepage:
    path:     /
    defaults: { _controller: MathiasCiqualBundle:Default:index }

mathias_ciqual_aliment:
    resource: "@MathiasCiqualBundle/Resources/config/routing/Aliment.yml"
    prefix:   /aliment