Mathias\Bundle\CiqualBundle\Entity\AlimentElementNutritif:
    type: entity
    table: null
    repositoryClass: Mathias\Bundle\CiqualBundle\Repository\AlimentElementNutritifRepository
    id:
#        id:
#            type: integer
#            id: true
#            generator:
#                strategy: AUTO
#            options:
#                unsigned: true
        aliment:
            associationKey: true
        elementNutritif:
            associationKey: true
    fields:
        valeur:
            type: string
            length: 255
    manyToOne:
        aliment:
            targetEntity: Mathias\Bundle\CiqualBundle\Entity\Aliment
            inversedBy: alimentElementNutritifs
        elementNutritif:
            targetEntity: Mathias\Bundle\CiqualBundle\Entity\ElementNutritif
    lifecycleCallbacks: {  }
