Mathias\Bundle\CiqualBundle\Entity\AlimentElementNutritif:
    type: entity
    table: null
    repositoryClass: Mathias\Bundle\CiqualBundle\Repository\AlimentElementNutritifRepository
    # l'id 'id' ne sert à rien dans ce cas, on doit utiliser la combinaison des deux entités afin de gagner en vitesse
    id:
        aliment:
            associationKey: true
        elementNutritif:
            associationKey: true
    fields:
        valeur:
            type: string
            length: 255
    manyToOne:
        aliment:
            targetEntity: Mathias\Bundle\CiqualBundle\Entity\Aliment
            inversedBy: alimentElementNutritifs
        elementNutritif:
            targetEntity: Mathias\Bundle\CiqualBundle\Entity\ElementNutritif
    lifecycleCallbacks: {  }
