Mathias\Bundle\CiqualBundle\Entity\Aliment:
    type: entity
    table: null
    repositoryClass: Mathias\Bundle\CiqualBundle\Repository\AlimentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        code:
            type: string
            length: 255
        nom:
            type: string
            length: 255
    manyToOne:
        famille:
            targetEntity: Mathias\Bundle\CiqualBundle\Entity\FamilleAliment
            inversedBy: aliments
    lifecycleCallbacks: {  }
