Mathias\Bundle\CiqualBundle\Entity\ElementNutritif:
    type: entity
    table: null
    repositoryClass: Mathias\Bundle\CiqualBundle\Repository\ElementNutritifRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            options:
                unsigned: true
    fields:
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }
